/**
 * Ship.js — Player ship (and NPC ship) physics entity.
 *
 * Ships are the only dynamically integrated objects. Everything else
 * (planets, moons, Solara) is on-rails via KeplerOrbit.
 *
 * Mass model:
 *   totalMass = hullMass + componentMass + fuelMass + cargoMass
 *   As fuel burns, fuelMass decreases, so the same thrust produces higher a.
 *
 * Resources:
 *   fuel    [0, maxFuel]  — burned by engines, traded at stations
 *   power   [0, maxPower] — consumed by energy weapons / shields; regenerates
 *   heat    [0, maxHeat]  — generated by engines/weapons; dissipated by radiators
 *   integrity [0, max]    — hull health; reaches 0 → ship destroyed
 */

import { Vec2 } from '../core/Vec2.js';

/** Standard gravity (m/s²) — used in Tsiolkovsky rocket equation. */
export const G0 = 9.80665;

export class Ship {
  /**
   * @param {object} opts
   * @param {Vec2}   opts.position     Initial world-space position (sim units)
   * @param {Vec2}   opts.velocity     Initial velocity (sim units/s)
   * @param {Loadout} opts.loadout     Active loadout defining mass and capabilities
   * @param {number} opts.fuel         Starting fuel mass (kg), defaults to max
   * @param {Array}  opts.cargos       Array of cargo items
   */
  constructor({
    position = Vec2.zero(),
    velocity = Vec2.zero(),
    loadout  = null,
    fuel     = null,
    cargos   = [],
    name     = 'UNKNOWN SHIP',
  } = {}) {
    // --- Physics ---
    this.position = position.clone();
    this.velocity = velocity.clone();

    // Previous-step state for render interpolation
    this._prevPosition = position.clone();
    this._prevVelocity = velocity.clone();

    // --- Loadout & Mass ---
    if (!loadout) throw new Error("Ship requires a Loadout");
    this.loadout = loadout;
    this.cargos  = cargos;   // Array of { mass: number, type: string, amount: number }
    this.fuel    = fuel !== null ? fuel : loadout.maxFuel;

    // --- Propulsion state ---
    this.heading   = 0;     // angle in radians (0 = +x = right)
    this.throttle  = 0;     // [0, 1] throttle level

    // --- Resources ---
    this.integrity = loadout.hull.integrity;
    this.power     = 100 + loadout.powerGen;  // start at max power (100 base + reactor)
    this.heat      = 0;

    // --- Identity ---
    this.name      = name;

    // --- Status flags ---
    this.destroyed    = false;
    this.disabled     = false;
    this.isPlayer     = false;

    // Accumulated gravitational acceleration this step (set by ShipSim)
    this._gravAcc = Vec2.zero();
  }

  // --- Dynamic Getters from Loadout ---

  get maxIntegrity() { return this.loadout.hull.integrity; }
  get maxFuel()      { return this.loadout.maxFuel; }
  get thrust()       { return this.loadout.totalThrust; }
  get isp()          { return this.loadout.netIsp; }
  get maxPower()     { return 100 + this.loadout.powerGen; }  // 100 base + reactor output
  get powerRegen()   { return 10 + this.loadout.powerGen; }   // Base 10 + reactor regen
  get maxHeat()      { return 100; } // Base heat cap before damage
  get heatDissipation() { return 10; } // Base radiator cap

  /**
   * Total mass of the ship right now (emptyMass + fuel + cargo).
   * This is the 'm' in F = ma.
   */
  get totalMass() {
    const cargoMass = this.cargos.reduce((sum, c) => sum + (c.mass || 0), 0);
    return this.loadout.emptyMass + this.fuel + cargoMass;
  }

  /** Current acceleration magnitude from active thrust (m/s²). */
  get currentAcceleration() {
    if (this.totalMass === 0) return 0;
    return (this.thrust * this.throttle) / this.totalMass;
  }

  /** Current acceleration in standard G (g-forces). */
  get gForce() {
    return this.currentAcceleration / G0;
  }

  /**
   * Returns the thrust vector at the current heading and throttle.
   * @returns {Vec2} Force vector (N)
   */
  thrustVector() {
    const F = this.thrust * this.throttle;
    return Vec2.fromAngle(this.heading, F);
  }

  /**
   * Fuel mass flow rate at current throttle (kg/s).
   * From Tsiolkovsky: ṁ = F / (Isp * g₀)
   */
  fuelFlowRate() {
    if (this.isp <= 0) return 0;
    const F = this.thrust * this.throttle;
    return F / (this.isp * G0);
  }

  /**
   * Burn engines for dt seconds.
   * Reduces fuel, thrust vector is handled by ShipSim calling thrustVector().
   * Called by ShipSim.step() so it only runs if throttle > 0 and fuel > 0.
   * @param {number} dt Delta-time (seconds)
   * @returns {number} Actual fuel burned this step (kg)
   */
  consumeFuel(dt) {
    if (this.throttle <= 0 || this.fuel <= 0 || this.isp <= 0) return 0;
    const burned = Math.min(this.fuelFlowRate() * dt, this.fuel);
    this.fuel -= burned;
    if (this.fuel <= 0) {
      this.fuel     = 0;
      this.throttle = 0;  // engine cuts out
    }
    return burned;
  }

  /**
   * Apply damage to hull integrity.
   */
  takeDamage(amount) {
    this.integrity -= amount;
    if (this.integrity <= 0) {
      if (!this.disabled) {
        this.integrity = 0;
        this.disabled = true;
        this.throttle = 0;
      } else {
        // Destroy if it takes substantial additional damage while disabled
        if (this.integrity <= -50) {
          this.destroyed = true;
        }
      }
    }
  }

  /**
   * Regenerate power, dissipate heat.
   */
  updateResources(dt) {
    // Power regens up to max
    this.power = Math.min(this.maxPower, this.power + this.powerRegen * dt);

    // Heat dissipates toward 0
    this.heat = Math.max(0, this.heat - this.heatDissipation * dt);

    // Overheating: damage modules at maxHeat
    if (this.heat >= this.maxHeat) {
      this.takeDamage(2 * dt);  // 2 hp/s thermal damage
    }
  }

  /** Store the current position/velocity as the previous frame state. */
  savePrevState() {
    this._prevPosition = this.position.clone();
    this._prevVelocity = this.velocity.clone();
  }

  /** Get interpolated position for rendering (between physics steps). */
  getRenderPosition(alpha) {
    return this._prevPosition.lerp(this.position, alpha);
  }

  /** Get the current world-space position. */
  getPosition() {
    return this.position.clone();
  }

  /** Return a lightweight snapshot of the ship's physics state. */
  getState() {
    return {
      position:  this.position.clone(),
      velocity:  this.velocity.clone(),
      fuel:      this.fuel,
      totalMass: this.totalMass,
      thrust:    this.thrust,
      isp:       this.isp,
      heading:   this.heading,
      throttle:  this.throttle,
    };
  }

  /** Restore a state snapshot (used by Trajectory after prediction run). */
  setState(s) {
    this.position  = s.position.clone();
    this.velocity  = s.velocity.clone();
    this.fuel      = s.fuel;
    this.heading   = s.heading;
    this.throttle  = s.throttle;
  }
}
