export const COMMODITY_CATEGORIES = {
    RAW: 'RAW',
    INTERMEDIATE: 'INTERMEDIATE',
    END_PRODUCT: 'END_PRODUCT'
};

export const COMMODITIES = {
    WATER_ICE: {
        id: 'WATER_ICE',
        name: 'Water Ice',
        category: COMMODITY_CATEGORIES.RAW,
        basePrice: 15,
        massPerUnit: 1.0,
        volumePerUnit: 1.0,
        isIllegal: false,
    },
    RAW_ORE: {
        id: 'RAW_ORE',
        name: 'Raw Ore',
        category: COMMODITY_CATEGORIES.RAW,
        basePrice: 25,
        massPerUnit: 2.0,
        volumePerUnit: 0.8,
        isIllegal: false,
    },
    HELIUM_3: {
        id: 'HELIUM_3',
        name: 'Helium-3',
        category: COMMODITY_CATEGORIES.RAW,
        basePrice: 200,
        massPerUnit: 0.5,
        volumePerUnit: 2.0,
        isIllegal: false,
    },
    BIOMASS: {
        id: 'BIOMASS',
        name: 'Biomass',
        category: COMMODITY_CATEGORIES.RAW,
        basePrice: 10,
        massPerUnit: 1.0,
        volumePerUnit: 1.5,
        isIllegal: false,
    },
    REFINED_METALS: {
        id: 'REFINED_METALS',
        name: 'Refined Metals',
        category: COMMODITY_CATEGORIES.INTERMEDIATE,
        basePrice: 100,
        massPerUnit: 1.5,
        volumePerUnit: 0.5,
        isIllegal: false,
    },
    PLASTICS: {
        id: 'PLASTICS',
        name: 'Plastics',
        category: COMMODITY_CATEGORIES.INTERMEDIATE,
        basePrice: 50,
        massPerUnit: 0.8,
        volumePerUnit: 1.2,
        isIllegal: false,
    },
    CHEMICALS: {
        id: 'CHEMICALS',
        name: 'Chemicals',
        category: COMMODITY_CATEGORIES.INTERMEDIATE,
        basePrice: 80,
        massPerUnit: 1.0,
        volumePerUnit: 1.0,
        isIllegal: false,
    },
    MACHINERY_PARTS: {
        id: 'MACHINERY_PARTS',
        name: 'Machinery Parts',
        category: COMMODITY_CATEGORIES.INTERMEDIATE,
        basePrice: 150,
        massPerUnit: 1.2,
        volumePerUnit: 1.5,
        isIllegal: false,
    },
    FOOD_PAKS: {
        id: 'FOOD_PAKS',
        name: 'Food Paks',
        category: COMMODITY_CATEGORIES.END_PRODUCT,
        basePrice: 40,
        massPerUnit: 0.5,
        volumePerUnit: 0.5,
        isIllegal: false,
    },
    MEDICINE: {
        id: 'MEDICINE',
        name: 'Medicine',
        category: COMMODITY_CATEGORIES.END_PRODUCT,
        basePrice: 250,
        massPerUnit: 0.2,
        volumePerUnit: 0.2,
        isIllegal: false,
    },
    ADVANCED_ELECTRONICS: {
        id: 'ADVANCED_ELECTRONICS',
        name: 'Advanced Electronics',
        category: COMMODITY_CATEGORIES.END_PRODUCT,
        basePrice: 500,
        massPerUnit: 0.5,
        volumePerUnit: 0.5,
        isIllegal: false,
    },
    LUXURIES: {
        id: 'LUXURIES',
        name: 'Luxuries',
        category: COMMODITY_CATEGORIES.END_PRODUCT,
        basePrice: 800,
        massPerUnit: 1.0,
        volumePerUnit: 1.0,
        isIllegal: false,
    },
    SHIP_COMPONENTS: {
        id: 'SHIP_COMPONENTS',
        name: 'Ship Components',
        category: COMMODITY_CATEGORIES.END_PRODUCT,
        basePrice: 1200,
        massPerUnit: 2.0,
        volumePerUnit: 2.0,
        isIllegal: false,
    },
    ILLEGAL_STIMS: {
        id: 'ILLEGAL_STIMS',
        name: 'Illegal Stims',
        category: COMMODITY_CATEGORIES.END_PRODUCT,
        basePrice: 1000,
        massPerUnit: 0.1,
        volumePerUnit: 0.2,
        isIllegal: true,
    }
};
